using System.Text;
using Il2CppDumper.Core.Containers;
using Il2CppDumper.Core.Model;

namespace Il2CppDumper.Core.Exporters;

public sealed class CppSdkExporter : IExporter
{
    public string Name => "C++ Modding SDK (il2cpp.h & Visual Studio Scaffolding)";

    public ExportResult Export(DumpContext context, string outputDirectory, ExportOptions options, Action<string>? logger = null)
    {
        var result = new ExportResult { Name = Name };
        if (!options.ExportCppSdk) return result;

        try
        {
            var sdkDir = Path.Combine(outputDirectory, "cpp-sdk");
            Directory.CreateDirectory(sdkDir);
            logger?.Invoke($"Exporting C++ Modding SDK to: {sdkDir}...");

            // 1. Generate il2cpp.h
            var headerPath = ExportHeader(context, sdkDir, logger);
            result.GeneratedFiles.Add(headerPath);

            // 2. Generate il2cpp-init.h
            var initPath = ExportInitHeader(context, sdkDir, logger);
            result.GeneratedFiles.Add(initPath);

            // 3. Generate sample hooking dllmain.cpp
            var dllMainPath = ExportDllMain(context, sdkDir, logger);
            result.GeneratedFiles.Add(dllMainPath);

            result.Success = true;
            logger?.Invoke($"C++ Modding SDK generated in {sdkDir}");
        }
        catch (Exception ex)
        {
            result.Success = false;
            result.Error = ex.Message;
            logger?.Invoke($"[Error] {Name} export failed: {ex.Message}");
        }

        return result;
    }

    private static string ExportHeader(DumpContext context, string sdkDir, Action<string>? logger)
    {
        var headerPath = Path.Combine(sdkDir, "il2cpp.h");
        using var writer = new StreamWriter(headerPath, false, Encoding.UTF8);

        writer.WriteLine("// Generated by Il2CppDumper");
        writer.WriteLine($"// Metadata Version: {context.MetadataVersion} | Unity Version: {context.UnityVersion}");
        writer.WriteLine($"// Architecture: {context.Architecture} | Format: {context.Format}");
        writer.WriteLine("// ===========================================================================");
        writer.WriteLine("#pragma once");
        writer.WriteLine("#include <cstdint>");
        writer.WriteLine("#include <cstddef>");
        writer.WriteLine();

        // 1. Standard Il2Cpp Object Header definition
        writer.WriteLine("// Base IL2CPP Object Header");
        writer.WriteLine("struct Il2CppClass;");
        writer.WriteLine("struct MonitorData;");
        writer.WriteLine("struct Il2CppObject {");
        writer.WriteLine("    Il2CppClass* klass;");
        writer.WriteLine("    MonitorData* monitor;");
        writer.WriteLine("};");
        writer.WriteLine();

        // 2. Forward Declarations
        writer.WriteLine("// Forward Declarations");
        foreach (var img in context.Images)
        {
            foreach (var type in img.Types)
            {
                if (!type.IsEnum)
                {
                    writer.WriteLine($"struct {SanitizeCpp(type.FullName)};");
                }
            }
        }
        writer.WriteLine();

        var is64Bit = context.Architecture is Architecture.Arm64 or Architecture.X64 or Architecture.Unknown;
        var headerSize = is64Bit ? 0x10 : 0x8;

        // 3. Struct definitions with memory-aligned layout and static_asserts
        foreach (var img in context.Images)
        {
            writer.WriteLine("// ---------------------------------------------------------------------------");
            writer.WriteLine($"// Assembly: {img.Name}");
            writer.WriteLine("// ---------------------------------------------------------------------------");

            foreach (var type in img.Types)
            {
                var cppName = SanitizeCpp(type.FullName);
                if (type.IsEnum)
                {
                    writer.WriteLine($"enum class {cppName} : int32_t {{");
                    foreach (var f in type.Fields.Where(f => f.IsConst))
                    {
                        writer.WriteLine($"    {SanitizeCpp(f.Name)},");
                    }
                    writer.WriteLine("};");
                    writer.WriteLine();
                    continue;
                }

                writer.WriteLine("#pragma pack(push, 1)");
                if (type.IsValueType)
                {
                    writer.WriteLine($"struct {cppName} {{");
                }
                else
                {
                    writer.WriteLine($"struct {cppName} : public Il2CppObject {{");
                }

                var currentOffset = type.IsValueType ? 0 : headerSize;
                var instanceFields = type.Fields
                    .Where(f => !f.IsStatic && !f.IsConst)
                    .OrderBy(f => f.Offset)
                    .ToList();

                for (var i = 0; i < instanceFields.Count; i++)
                {
                    var field = instanceFields[i];
                    var fieldName = SanitizeCpp(field.Name);

                    if (field.Offset < 0 || field.AddressConfidence == AddressConfidence.Unknown)
                    {
                        writer.WriteLine($"    void* {fieldName}; // Offset: UNKNOWN ({field.TypeName})");
                        continue;
                    }

                    if (field.Offset > currentOffset)
                    {
                        var pad = field.Offset - currentOffset;
                        writer.WriteLine($"    uint8_t _pad_0x{currentOffset:X}[0x{pad:X}];");
                        currentOffset = field.Offset;
                    }

                    var nextOffset = (i + 1 < instanceFields.Count) ? instanceFields[i + 1].Offset : -1;
                    var (cppType, typeSize) = MapCppType(field.TypeName, is64Bit);

                    if (typeSize > 0)
                    {
                        writer.WriteLine($"    {cppType} {fieldName}; // Offset: 0x{field.Offset:X}");
                        currentOffset += typeSize;
                    }
                    else if (nextOffset > field.Offset)
                    {
                        var fieldSpan = nextOffset - field.Offset;
                        writer.WriteLine($"    uint8_t {fieldName}[0x{fieldSpan:X}]; // Offset: 0x{field.Offset:X} ({field.TypeName})");
                        currentOffset = nextOffset;
                    }
                    else
                    {
                        var fallbackSize = is64Bit ? 8 : 4;
                        writer.WriteLine($"    void* {fieldName}; // Offset: 0x{field.Offset:X} ({field.TypeName})");
                        currentOffset += fallbackSize;
                    }
                }

                writer.WriteLine("};");
                writer.WriteLine("#pragma pack(pop)");

                // Compile-time offset validation (Part 22)
                foreach (var field in instanceFields.Where(f => f.Offset >= 0 && f.AddressConfidence != AddressConfidence.Unknown))
                {
                    var fName = SanitizeCpp(field.Name);
                    writer.WriteLine($"static_assert(offsetof({cppName}, {fName}) == 0x{field.Offset:X}, \"Offset of {fName} mismatch in {cppName}\");");
                }
                writer.WriteLine();

                // Method function pointer typedefs with unique stable hash suffix (Part 22)
                foreach (var m in type.Methods)
                {
                    if (m.Rva == 0 || m.AddressConfidence == AddressConfidence.Unknown) continue;

                    var paramTypes = string.Join(",", m.Parameters.Select(p => p.TypeName));
                    var hashVal = ((uint)paramTypes.GetHashCode() & 0xFFFFFF).ToString("X6");
                    var typedefName = $"{cppName}_{SanitizeCpp(m.Name)}_{hashVal}_t";
                    var retType = MapCppType(m.ReturnType, is64Bit).CppType;

                    var paramList = $"{cppName}* __this";
                    if (m.Parameters.Count > 0)
                    {
                        var mappedParams = m.Parameters.Select(p =>
                        {
                            var pType = MapCppType(p.TypeName, is64Bit).CppType;
                            return $"{pType} {SanitizeCpp(p.Name)}";
                        });
                        paramList += ", " + string.Join(", ", mappedParams);
                    }
                    paramList += ", const void* method";

                    writer.WriteLine($"// RVA: 0x{m.Rva:X} | Slot: {m.Slot}");
                    writer.WriteLine($"typedef {retType} (*{typedefName})({paramList});");
                }
                writer.WriteLine();
            }
        }

        logger?.Invoke($"Wrote: {headerPath}");
        return headerPath;
    }

    private static (string CppType, int Size) MapCppType(string? csharpType, bool is64Bit)
    {
        if (string.IsNullOrWhiteSpace(csharpType))
            return ("void", 0);

        var trimmed = csharpType.Trim();
        var ptrSize = is64Bit ? 8 : 4;

        if (trimmed.EndsWith('*') || trimmed.EndsWith('&') || trimmed.EndsWith("[]"))
            return ("void*", ptrSize);

        return trimmed switch
        {
            "void" or "System.Void" => ("void", 0),
            "bool" or "System.Boolean" => ("bool", 1),
            "byte" or "System.Byte" => ("uint8_t", 1),
            "sbyte" or "System.SByte" => ("int8_t", 1),
            "char" or "System.Char" => ("char16_t", 2),
            "short" or "System.Int16" => ("int16_t", 2),
            "ushort" or "System.UInt16" => ("uint16_t", 2),
            "int" or "System.Int32" => ("int32_t", 4),
            "uint" or "System.UInt32" => ("uint32_t", 4),
            "long" or "System.Int64" => ("int64_t", 8),
            "ulong" or "System.UInt64" => ("uint64_t", 8),
            "float" or "System.Single" => ("float", 4),
            "double" or "System.Double" => ("double", 8),
            "string" or "System.String" => ("void*", ptrSize),
            "object" or "System.Object" => ("void*", ptrSize),
            "IntPtr" or "System.IntPtr" => ("void*", ptrSize),
            "UIntPtr" or "System.UIntPtr" => ("void*", ptrSize),
            _ => ("void*", 0)
        };
    }

    private static string ExportInitHeader(DumpContext context, string sdkDir, Action<string>? logger)
    {
        var initPath = Path.Combine(sdkDir, "il2cpp-init.h");
        using var writer = new StreamWriter(initPath, false, Encoding.UTF8);

        writer.WriteLine("// Auto-generated runtime address resolver");
        writer.WriteLine("#pragma once");
        writer.WriteLine("#include <cstdint>");
        writer.WriteLine("#if defined(_WIN32)");
        writer.WriteLine("#include <windows.h>");
        writer.WriteLine("#else");
        writer.WriteLine("#include <dlfcn.h>");
        writer.WriteLine("#endif");
        writer.WriteLine();
        writer.WriteLine("inline uintptr_t GetIl2CppBase()");
        writer.WriteLine("{");
        writer.WriteLine("#if defined(_WIN32)");
        writer.WriteLine("    return reinterpret_cast<uintptr_t>(GetModuleHandleA(\"GameAssembly.dll\"));");
        writer.WriteLine("#else");
        writer.WriteLine("    return reinterpret_cast<uintptr_t>(dlopen(\"libil2cpp.so\", RTLD_NOLOAD));");
        writer.WriteLine("#endif");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("template <typename T>");
        writer.WriteLine("inline T ResolveMethod(uintptr_t rva)");
        writer.WriteLine("{");
        writer.WriteLine("    uintptr_t base = GetIl2CppBase();");
        writer.WriteLine("    if (!base) return nullptr;");
        writer.WriteLine("    return reinterpret_cast<T>(base + rva);");
        writer.WriteLine("}");

        logger?.Invoke($"Wrote: {initPath}");
        return initPath;
    }

    private static string ExportDllMain(DumpContext context, string sdkDir, Action<string>? logger)
    {
        var dllMainPath = Path.Combine(sdkDir, "dllmain.cpp");
        using var writer = new StreamWriter(dllMainPath, false, Encoding.UTF8);

        writer.WriteLine("// ===========================================================================");
        writer.WriteLine("// MinHook / Dobby Function Hooking Scaffold");
        writer.WriteLine("// ===========================================================================");
        writer.WriteLine("#include \"il2cpp.h\"");
        writer.WriteLine("#include \"il2cpp-init.h\"");
        writer.WriteLine();
        writer.WriteLine("#if defined(_WIN32)");
        writer.WriteLine("#include <windows.h>");
        writer.WriteLine();
        writer.WriteLine("DWORD WINAPI MainThread(LPVOID lpParam)");
        writer.WriteLine("{");
        writer.WriteLine("    while (!GetIl2CppBase()) {");
        writer.WriteLine("        Sleep(100);");
        writer.WriteLine("    }");
        writer.WriteLine("    return 0;");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)");
        writer.WriteLine("{");
        writer.WriteLine("    if (ul_reason_for_call == DLL_PROCESS_ATTACH) {");
        writer.WriteLine("        DisableThreadLibraryCalls(hModule);");
        writer.WriteLine("        CreateThread(nullptr, 0, MainThread, hModule, 0, nullptr);");
        writer.WriteLine("    }");
        writer.WriteLine("    return TRUE;");
        writer.WriteLine("}");
        writer.WriteLine("#endif");

        logger?.Invoke($"Wrote: {dllMainPath}");
        return dllMainPath;
    }

    private static string SanitizeCpp(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_unnamed";
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
            {
                sb.Append(ch);
            }
            else
            {
                sb.Append('_');
            }
        }
        var res = sb.ToString();
        if (char.IsDigit(res[0])) res = "_" + res;
        return res;
    }
}
