using System.Text;
using System.Text.Json;
using Il2CppDumper.Core.Model;

namespace Il2CppDumper.Core.Exporters;

public sealed class DumpCsExporter : IExporter
{
    public string Name => "C# Static Dump (dump.cs & script.json)";

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate", "do",
        "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
        "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int",
        "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
        "object", "operator", "out", "override", "params", "private", "protected", "public",
        "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc",
        "static", "string", "struct", "switch", "this", "throw", "true", "try",
        "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };

    public ExportResult Export(DumpContext context, string outputDirectory, ExportOptions options, Action<string>? logger = null)
    {
        var result = new ExportResult { Name = Name };
        try
        {
            Directory.CreateDirectory(outputDirectory);

            if (options.ExportDumpCs)
            {
                logger?.Invoke("Generating dump.cs...");
                var dumpCsPath = Path.Combine(outputDirectory, "dump.cs");
                using var writer = new StreamWriter(dumpCsPath, false, Encoding.UTF8);

                writer.WriteLine("// Generated by Il2CppDumper");
                writer.WriteLine($"// Metadata Version: {context.MetadataVersion}");
                writer.WriteLine($"// Unity Version: {context.UnityVersion}");
                writer.WriteLine($"// Architecture: {context.Architecture} | Format: {context.Format}");
                writer.WriteLine($"// Analysis Mode: {context.AnalysisMode} | Address Confidence: {context.AddressConfidence}");
                writer.WriteLine($"// Dump Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
                writer.WriteLine($"// Assemblies: {context.TotalImages} | Types: {context.TotalTypes} | Methods: {context.TotalMethods}");
                writer.WriteLine("// ===========================================================================");
                writer.WriteLine();

                foreach (var img in context.Images)
                {
                    writer.WriteLine($"// Image: {img.Name} - Types: {img.Types.Count}");

                    var namespaceGroups = img.Types.GroupBy(t => t.Namespace);
                    foreach (var group in namespaceGroups)
                    {
                        var ns = group.Key;
                        var hasNamespace = !string.IsNullOrEmpty(ns);
                        var indent = hasNamespace ? "\t" : "";

                        if (hasNamespace)
                        {
                            writer.WriteLine($"namespace {SanitizeNamespace(ns)}");
                            writer.WriteLine("{");
                        }

                        foreach (var type in group)
                        {
                            writer.WriteLine($"{indent}// TypeDefIndex: {type.TypeDefIndex} | Assembly: {img.Name}");
                            if (!string.IsNullOrEmpty(type.BaseTypeName))
                            {
                                writer.WriteLine($"{indent}// BaseType: {type.BaseTypeName}");
                            }

                            var typeKind = type.IsEnum ? "enum" : (type.IsValueType ? "struct" : (type.IsInterface ? "interface" : "class"));
                            var access = type.IsPublic ? "public" : "internal";
                            var abstractModifier = (type.IsAbstract && !type.IsInterface && !type.IsValueType) ? "abstract " : "";

                            writer.WriteLine($"{indent}{access} {abstractModifier}{typeKind} {SanitizeIdentifier(type.Name)}");
                            writer.WriteLine($"{indent}{{");

                            // Fields
                            if (type.Fields.Count > 0)
                            {
                                writer.WriteLine($"{indent}\t// Fields");
                                foreach (var field in type.Fields)
                                {
                                    var fieldAccess = field.IsPublic ? "public" : (field.IsPrivate ? "private" : "internal");
                                    var staticMod = field.IsStatic ? (field.IsConst ? "const " : "static ") : "";
                                    var offsetStr = (field.Offset >= 0 && field.AddressConfidence != AddressConfidence.Unknown)
                                        ? $"0x{field.Offset:X}"
                                        : "UNKNOWN";
                                    writer.WriteLine($"{indent}\t{fieldAccess} {staticMod}{SanitizeType(field.TypeName)} {SanitizeIdentifier(field.Name)}; // Offset: {offsetStr}");
                                }
                                writer.WriteLine();
                            }

                            // Properties
                            if (type.Properties.Count > 0)
                            {
                                writer.WriteLine($"{indent}\t// Properties");
                                foreach (var prop in type.Properties)
                                {
                                    var accessors = "";
                                    if (prop.Getter != null) accessors += "get; ";
                                    if (prop.Setter != null) accessors += "set; ";
                                    if (string.IsNullOrEmpty(accessors)) accessors = "get; ";
                                    writer.WriteLine($"{indent}\tpublic {SanitizeType(prop.TypeName)} {SanitizeIdentifier(prop.Name)} {{ {accessors}}}");
                                }
                                writer.WriteLine();
                            }

                            // Methods
                            if (type.Methods.Count > 0)
                            {
                                writer.WriteLine($"{indent}\t// Methods");
                                foreach (var method in type.Methods)
                                {
                                    var isUnknown = method.AddressConfidence == AddressConfidence.Unknown || method.Rva == 0;
                                    var rvaStr = !isUnknown ? $"0x{method.Rva:X}" : "UNKNOWN";
                                    var offsetStr = (method.FileOffset >= 0 && !isUnknown) ? $"0x{method.FileOffset:X}" : "UNKNOWN";
                                    var vaStr = (method.MethodPointer != 0 && !isUnknown) ? $"0x{method.MethodPointer:X}" : "UNKNOWN";
                                    var tokenStr = method.Token != 0 ? $" Token: 0x{method.Token:X8}" : "";

                                    writer.WriteLine($"{indent}\t// RVA: {rvaStr} Offset: {offsetStr} VA: {vaStr}{tokenStr} Slot: {method.Slot}");

                                    var methodAccess = method.IsPublic ? "public" : (method.IsPrivate ? "private" : "internal");
                                    var staticMod = method.IsStatic ? "static " : "";
                                    var virtMod = method.IsVirtual ? "virtual " : "";
                                    var absMod = method.IsAbstract ? "abstract " : "";

                                    var paramList = string.Join(", ", method.Parameters.Select(p => $"{SanitizeType(p.TypeName)} {SanitizeIdentifier(p.Name)}"));
                                    writer.WriteLine($"{indent}\t{methodAccess} {staticMod}{virtMod}{absMod}{SanitizeType(method.ReturnType)} {SanitizeIdentifier(method.Name)}({paramList}) {{ }}");
                                }
                            }

                            writer.WriteLine($"{indent}}}");
                            writer.WriteLine();
                        }

                        if (hasNamespace)
                        {
                            writer.WriteLine("}");
                            writer.WriteLine();
                        }
                    }
                }

                result.GeneratedFiles.Add(dumpCsPath);
                logger?.Invoke($"Wrote: {dumpCsPath}");
            }

            if (options.ExportScriptJson)
            {
                logger?.Invoke("Generating script.json and stringliteral.json...");
                ExportScriptJsonInternal(context, outputDirectory, result, logger);
            }

            result.Success = true;
        }
        catch (Exception ex)
        {
            result.Success = false;
            result.Error = ex.Message;
            logger?.Invoke($"[Error] {Name} export failed: {ex.Message}");
        }

        return result;
    }

    private static void ExportScriptJsonInternal(DumpContext context, string outputDirectory, ExportResult result, Action<string>? logger)
    {
        var scriptMethods = new List<ScriptMethodEntry>();
        foreach (var img in context.Images)
        {
            foreach (var type in img.Types)
            {
                foreach (var method in type.Methods)
                {
                    if (method.Rva == 0 && method.MethodPointer == 0) continue;

                    scriptMethods.Add(new ScriptMethodEntry
                    {
                        Address = method.MethodPointer != 0 ? method.MethodPointer : method.Rva,
                        Rva = method.Rva,
                        Offset = method.FileOffset,
                        Name = $"{type.FullName}::{method.Name}",
                        Signature = method.Signature,
                        TypeName = type.FullName
                    });
                }
            }
        }

        var jsonOptions = new JsonSerializerOptions { WriteIndented = true };
        var scriptJsonPath = Path.Combine(outputDirectory, "script.json");
        var scriptJson = new
        {
            MetadataVersion = context.MetadataVersion,
            UnityVersion = context.UnityVersion,
            Architecture = context.Architecture.ToString(),
            TotalMethods = scriptMethods.Count,
            ScriptMethod = scriptMethods,
            ScriptMethods = scriptMethods
        };
        File.WriteAllText(scriptJsonPath, JsonSerializer.Serialize(scriptJson, jsonOptions));
        result.GeneratedFiles.Add(scriptJsonPath);
        logger?.Invoke($"Wrote: {scriptJsonPath} ({scriptMethods.Count} mapped methods)");

        // String literals (Part 12: preserves Index, Value, Offset, Length)
        if (context.StringLiterals.Count > 0)
        {
            var strJsonPath = Path.Combine(outputDirectory, "stringliteral.json");
            File.WriteAllText(strJsonPath, JsonSerializer.Serialize(context.StringLiterals, jsonOptions));
            result.GeneratedFiles.Add(strJsonPath);
            logger?.Invoke($"Wrote: {strJsonPath} ({context.StringLiterals.Count} strings)");
        }
    }

    public static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_unnamed";
        if (name is ".ctor" or ".cctor") return name;

        var sb = new StringBuilder(name.Length + 4);
        var first = true;
        foreach (var ch in name)
        {
            if (first && char.IsDigit(ch))
            {
                sb.Append('_');
            }
            first = false;

            if (char.IsLetterOrDigit(ch) || ch == '_')
            {
                sb.Append(ch);
            }
            else
            {
                sb.Append('_');
            }
        }

        var cleaned = sb.ToString();
        if (string.IsNullOrWhiteSpace(cleaned)) cleaned = "_unnamed";
        if (CSharpKeywords.Contains(cleaned))
        {
            return "@" + cleaned;
        }

        return cleaned;
    }

    private static string SanitizeNamespace(string ns)
    {
        if (string.IsNullOrEmpty(ns)) return string.Empty;
        var parts = ns.Split('.');
        return string.Join('.', parts.Select(SanitizeIdentifier));
    }

    public static string SanitizeType(string typeName)
    {
        if (string.IsNullOrEmpty(typeName)) return "void";
        return typeName.Replace('`', '_');
    }

    private sealed class ScriptMethodEntry
    {
        public ulong Address { get; set; }
        public ulong Rva { get; set; }
        public long Offset { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Signature { get; set; } = string.Empty;
        public string TypeName { get; set; } = string.Empty;
    }
}
